### PR TITLE
Resolve issue #16

### PR DESCRIPTION
**Pull request by cpdeethree**
Looks at tokens before parsing and performs a lookahead to collapse strings into a single token.

### CODE REVIEW

**Comment by mafintosh** [comment]
:+1:

**Comment by mafintosh** [comment]
Released in 2.0.4

**Comment by cpdeethree** [comment]
Thanks for quickly merging! Could you update NPM when you get the chance?

**Comment by mafintosh** [comment]
I did that already. It should be out in 2.0.4

**Comment by cpdeethree** [comment]
Whoops I was looking at the old repository https://www.npmjs.com/package/protobuf-schema 

Thanks again!

**Pull request merged**
