### PR TITLE
Fix tokenizing of comment after closing brace of last message

### PR DESCRIPTION
**Pull request by hvoecking**

### CODE REVIEW

**Comment by hvoecking** [comment]
Hi, I noticed that the tokenizer emits an empty token if a comment is put after the closing brace of the last message definition in a protobuf schema

**Comment by mafintosh** [comment]
Awesome thanks!

**Comment by mafintosh** [comment]
Out in 2.0.3

**Comment by hvoecking** [comment]
Wow, thanks for the quick action!

**Pull request merged**
