### PR TITLE
fix: update tokenizer to handle options with spaces

### PR DESCRIPTION
**Pull request by mkotelnikov**
Slight changes in the tokenizer to accept quoted option values

 Fix mafintosh/protocol-buffers-schema#55

### CODE REVIEW

**Comment by mafintosh** [comment]
Can you explain a bit how this fix works? Not fully sure I follow it.

**Comment by mkotelnikov** [comment]
I just remove all quoted strings, put temporarily in the `replacements` list, and replace them in the original string by theirs IDs (sequences like that: `$ID$` where `ID` is the replaced sequence position in a list). This done by the `removeQuotedLines` function.
After that the whole string with replaced quoted fragments is splitted as before to tokens. At the end I replace back tokens like `$ID$` by quoted strings from the `replacements` list (function `restoreQuotedLines`).

What do you think about this approach?

**Comment by mafintosh** [comment]
Ah ok, ya sounds good.

**Comment by mafintosh** [comment]
3.5.0

**Pull request merged**
